name: hello world
on: workflow_dispatch
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
    - name: Build step 
      run:
        echo "A Build step"
  test: 
    runs-on: ubuntu-latest 
    steps: 
    - name: Test step 
      run:
        echo "Running..."
  Deploy: 
      runs-on: ubuntu-latest 
      steps: 
      - name: Deploy step 
        run:
          echo "Deployig the app"
              
              
      
        
    
