name: hello world
on: workflow_dispatch
jobs: 
  hello: 
    runs-on: ubuntu-latest 
    steps: 
    - name: hello steps 
      run: |
        echo "Line one"
        echo "Line two"
      
        
    
